global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'house-price-api'
    static_configs:
      - targets: ['{{cookiecutter.project_slug}}-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
